// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"context"
)

type Querier interface {
	CreateTodo(ctx context.Context, title string) (Todo, error)
	// 已軟刪除的查不到：對 API 的呼叫端來說，刪掉就是不存在。
	GetTodo(ctx context.Context, id int64) (Todo, error)
	ListTodos(ctx context.Context, arg ListTodosParams) ([]Todo, error)
	// 軟刪除：打時間戳，不真的刪除資料列。
	//
	// WHERE 帶 deleted_at IS NULL 有兩個作用：重複刪除會影響 0 列（handler 回 404，
	// 跟「本來就不存在」同一個結果，對呼叫端來說語意一致），
	// 而且不會把第一次的刪除時間覆蓋掉。
	SoftDeleteTodo(ctx context.Context, id int64) (int64, error)
	// title 與 completed 都是選填（PATCH 語意）：沒帶的欄位維持原值。
	// 用 COALESCE 而不是在 Go 那邊拼 SQL，可選欄位再多也只有這一句。
	// 加上 deleted_at IS NULL：已刪除的不能再被改。
	UpdateTodo(ctx context.Context, arg UpdateTodoParams) (Todo, error)
}

var _ Querier = (*Queries)(nil)
