// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: todo.sql

package db

import (
	"context"
	"database/sql"
)

const createTodo = `-- name: CreateTodo :one
INSERT INTO todos (
    title
) VALUES (
    $1
) RETURNING id, title, completed, created_at, deleted_at
`

func (q *Queries) CreateTodo(ctx context.Context, title string) (Todo, error) {
	row := q.db.QueryRowContext(ctx, createTodo, title)
	var i Todo
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Completed,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getTodo = `-- name: GetTodo :one
SELECT id, title, completed, created_at, deleted_at FROM todos
WHERE id = $1 AND deleted_at IS NULL
LIMIT 1
`

// 已軟刪除的查不到：對 API 的呼叫端來說，刪掉就是不存在。
func (q *Queries) GetTodo(ctx context.Context, id int64) (Todo, error) {
	row := q.db.QueryRowContext(ctx, getTodo, id)
	var i Todo
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Completed,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listTodos = `-- name: ListTodos :many
SELECT id, title, completed, created_at, deleted_at FROM todos
WHERE deleted_at IS NULL
ORDER BY id
LIMIT $1
OFFSET $2
`

type ListTodosParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListTodos(ctx context.Context, arg ListTodosParams) ([]Todo, error) {
	rows, err := q.db.QueryContext(ctx, listTodos, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Todo{}
	for rows.Next() {
		var i Todo
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Completed,
			&i.CreatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteTodo = `-- name: SoftDeleteTodo :execrows
UPDATE todos
SET deleted_at = now()
WHERE id = $1 AND deleted_at IS NULL
`

// 軟刪除：打時間戳，不真的刪除資料列。
//
// WHERE 帶 deleted_at IS NULL 有兩個作用：重複刪除會影響 0 列（handler 回 404，
// 跟「本來就不存在」同一個結果，對呼叫端來說語意一致），
// 而且不會把第一次的刪除時間覆蓋掉。
func (q *Queries) SoftDeleteTodo(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, softDeleteTodo, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateTodo = `-- name: UpdateTodo :one
UPDATE todos
SET
    title = COALESCE($1, title),
    completed = COALESCE($2, completed)
WHERE id = $3 AND deleted_at IS NULL
RETURNING id, title, completed, created_at, deleted_at
`

type UpdateTodoParams struct {
	Title     sql.NullString `json:"title"`
	Completed sql.NullBool   `json:"completed"`
	ID        int64          `json:"id"`
}

// title 與 completed 都是選填（PATCH 語意）：沒帶的欄位維持原值。
// 用 COALESCE 而不是在 Go 那邊拼 SQL，可選欄位再多也只有這一句。
// 加上 deleted_at IS NULL：已刪除的不能再被改。
func (q *Queries) UpdateTodo(ctx context.Context, arg UpdateTodoParams) (Todo, error) {
	row := q.db.QueryRowContext(ctx, updateTodo, arg.Title, arg.Completed, arg.ID)
	var i Todo
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Completed,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}
